# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 00:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countrydata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='continent',
            name='countries',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='continents', to='countrydata.Country'),
        ),
        migrations.AlterField(
            model_name='continent',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
